### ISSUE TITLE
 unexpected keyword argument 'bypass_url' with python-novaclient 2012.1

### ISSUE THREAD

**Issue by sdouche** [pycontribs/pyrax#3]
Cannot authenticate with the last version of python-novacllent:

Traceback (most recent call last):
  File "./bin/python", line 52, in <module>
    exec(compile(**file__f.read(), __file**, "exec"))
  File "test.py", line 3, in <module>
    pyrax.set_credential_file('/home/sdouche/.rackspace_cloud_credentials')
  File "/home/sdouche/src/sact/internal/sact.vmcloud/eggs/pyrax-1.1.6b-py2.7.egg/pyrax/**init**.py", line 207, in set_credential_file
    connect_to_services()
  File "/home/sdouche/src/sact/internal/sact.vmcloud/eggs/pyrax-1.1.6b-py2.7.egg/pyrax/**init**.py", line 257, in connect_to_services
    cloudservers = connect_to_cloudservers()
  File "/home/sdouche/src/sact/internal/sact.vmcloud/eggs/pyrax-1.1.6b-py2.7.egg/pyrax/**init**.py", line 174, in _wrapped
    return fnc(_args, *_kwargs)
  File "/home/sdouche/src/sact/internal/sact.vmcloud/eggs/pyrax-1.1.6b-py2.7.egg/pyrax/__init__.py", line 300, in connect_to_cloudservers
    region_name=region, service_type="compute")
TypeError: **init**() got an unexpected keyword argument 'bypass_url'

It works with python-novaclient 2.10.0. Please pin this version in the setup.py file.
